"""Nox sessions for Blaine local verification.

Nox is the thin named-workflow / orchestration layer. It does NOT reimplement
tests or copy suite logic: it invokes the canonical verification CLI, which
discovers suites additively and drives the scheduler.

Sessions
--------
hermetic
    Run every HERMETIC suite directly (no host services, no Restate queue).
completion_contract
    Run the E1.0 Completion Contract hermetic qualification.
scheduler
    Run the deterministic scheduler unit tests.
pre_handoff
    The canonical pre-handoff sequence: scheduler self-tests + all hermetic
    suites. Host-bound suites are submitted to the Restate scheduler
    separately; they are deliberately not bundled here so a busy shared Restate
    never blocks the hermetic pre-handoff checks.

Adding a suite
--------------
Do NOT edit this file. Add a suite module under ``verification/suites/`` with a
top-level ``SUITE``; it is discovered automatically. The ``hermetic`` and
``pre_handoff`` sessions pick it up with zero change here, keeping this file
from becoming a cross-worktree edit hotspot.
"""
import nox
import os

# The shared runtime venv that carries pytest / restate-sdk / nox. Overridable.
PY = os.environ.get("BLAINE_PYTHON") or "/home/leofuso/workspace/blaine/.local/runtime-venv/bin/python"


def _hermetic_suites() -> list[str]:
    from verification.suite import discover_suites, VerificationClass
    return sorted(name for name, suite in discover_suites().items()
                  if suite.verification_class is VerificationClass.HERMETIC)


@nox.session
def hermetic(session: nox.Session) -> None:
    """Run every HERMETIC suite directly. No host services, no Restate queue."""
    suites = _hermetic_suites()
    if not suites:
        session.log("no HERMETIC suites discovered")
        return
    for name in suites:
        session.log(f"== hermetic suite: {name} ==")
        session.run(PY, "-m", "verification.cli", "run", name, external=True)


@nox.session
def completion_contract(session: nox.Session) -> None:
    """E1.0 Completion Contract hermetic qualification."""
    session.run(PY, "-m", "verification.cli", "run", "completion-contract",
                external=True)


@nox.session
def scheduler(session: nox.Session) -> None:
    """Deterministic local verification scheduler unit tests."""
    session.run(PY, "-m", "pytest", "verification/tests.py", "-q", external=True)


@nox.session
def pre_handoff(session: nox.Session) -> None:
    """Canonical pre-handoff verification (scheduler self-tests + hermetic).

    Host-bound suites are NOT run here; submit them to the Restate host
    scheduler separately. See docs/verification.md for the canonical command.
    """
    session.run(PY, "-m", "pytest", "verification/tests.py", "-q", external=True)
    hermetic(session)
